name: flutter_application_1
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  get: 4.6.6
  image_picker: ^1.0.4
  webview_flutter: ^4.4.1
  firebase_messaging: ^14.7.4
  firebase_core: ^2.22.0
  appwrite: ^11.0.0
  firebase_auth: ^4.13.0
  http: ^1.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  
  
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - lib/app/data/Assets/


