// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1fbAhCAXlSOlM16-LuzLXATPF4o8vbyA',
    appId: '1:771602306203:web:3f3919ee6c0bec4f3ae23e',
    messagingSenderId: '771602306203',
    projectId: 'cinemaxapp-4bd87',
    authDomain: 'cinemaxapp-4bd87.firebaseapp.com',
    storageBucket: 'cinemaxapp-4bd87.appspot.com',
    measurementId: 'G-HSMGV95NPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhcLS4tAps1szBL6GO1ZeMco7ziz0uJgg',
    appId: '1:771602306203:android:85cf0fe2e806c9cb3ae23e',
    messagingSenderId: '771602306203',
    projectId: 'cinemaxapp-4bd87',
    storageBucket: 'cinemaxapp-4bd87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjQUSy3IBdgO7P3J0d2alD9cHpXmlCJs',
    appId: '1:771602306203:ios:07db0577b02719043ae23e',
    messagingSenderId: '771602306203',
    projectId: 'cinemaxapp-4bd87',
    storageBucket: 'cinemaxapp-4bd87.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzjQUSy3IBdgO7P3J0d2alD9cHpXmlCJs',
    appId: '1:771602306203:ios:b624cc75ed3d52163ae23e',
    messagingSenderId: '771602306203',
    projectId: 'cinemaxapp-4bd87',
    storageBucket: 'cinemaxapp-4bd87.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
